spring.application.name=notification-service

#Path con el que se accederá el endpoint
server.servlet.context-path=/taskly-u/notification/v1

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true